django_level_four/learn_templates/basic_app/urls.py
from django.urls import path
from . import views

# TEMPLATE TAGGING - setting a global name for the app
app_name = 'basic_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:look_name>/<str:look_section>/', views.relative, name='relative'),
    path('other', views.other, name='other')
]

django_level_four/learn_templates/learn_templates/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic_app.urls')),
]

django_level_four/learn_templates/basic_app/models.py
from django.db import models

# Create your models here.

django_level_four/learn_templates/basic_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

names = ['Feb', 'Mar', 'Apr']
sections = ['1', '2', '3']


def index(request):
    return render(request, 'basic_app/index.html', {'names': names})


def relative(request, look_name, look_section):
    current_section = look_section
    current_name = look_name
    if look_name in names and look_section in sections:
        return render(request, 'basic_app/relative_url_templates.html', {'names': names,
                                                                         'sections': sections,
                                                                         'active_tab': current_name,
                                                                         'active_section': current_section})
    else:
        return HttpResponse('Error 404, Page does not exist!')


def other(request):
    return render(request, 'basic_app/other.html', {'names': names})

django_level_four/learn_templates/templates/basic_app/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
          <div class="col-2">
              <a class="navbar-brand" href="{% url 'basic_app:index' %}">Navbar BRAND</a>
          </div>

          <div class="col-10">
              <ul class="navbar-nav">

                  <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'basic_app:index' %}">Home</a></li>
                  <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'basic_app:other' %}">Other</a></li>

                  {% if names %}
                    {% for name in names %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:relative' look_name=name look_section=1 %}" role="button">{{ name }}</a></li>
                    {% endfor %}
                  {% endif %}
              </ul>
          </div>
      </div>
    </nav>

    <div class="container">
        {% block body_block %}
        <!-- Anything outside of this will be inherited if you extend!-->
        {% endblock %}
    </div>
</body>

</html>

django_level_four/learn_templates/templates/basic_app/index.html
<!doctype html>
{% extends "basic_app/base.html" %}
{% block body_block %}

    <h1>WELCOME TO INDEX</h1>
    <h2>This is index.html page showing!</h2>

{% endblock %}

django_level_four/learn_templates/templates/basic_app/other.html
<!doctype html>
{% extends "basic_app/base.html" %}
{% block body_block %}


<h1>WELCOME TO OTHER</h1>
<h2>This is an example of template inheritance!</h2>

        <a href="{% url 'basic_app:index' %}">The index page</a>
{% endblock %}

django_level_four/learn_templates/templates/basic_app/relative_url_templates.html
<!doctype html>
{% extends "basic_app/base.html" %}
{% block body_block %}

    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'basic_app:other' %}">The other page</a><br>
    <a href="{% url 'basic_app:index' %}">The index page</a>

<div class="container-fluid row">
    <!-- Col left-->
  <div class="col-lg-7" style="text-align:center">
    <!-- Tab panes img-->
    <div class="tab-content">
      <div id="target1-img" class="container tab-pane{% if active_section == '1' %} active {% endif %}"><br>
        <img alt="earth" src="https://i.pinimg.com/originals/15/4f/8f/154f8f3dd81a4cd2da2c82162173cd07.png" title="earth" style="width:40%">
      </div>
      <div id="target2-img" class="container tab-pane fade{% if active_section == '2' %} active show {% endif %}"><br>
        <img alt="earth-internal" src="https://images.theconversation.com/files/283241/original/file-20190709-44437-lazrcy.png?ixlib=rb-1.1.0&q=45&auto=format&w=1000&fit=clip" title="earth-internal" style="width:50%">
      </div>
      <div id="target3-img" class="container tab-pane fade{% if active_section == '3' %} active show {% endif %}"><br>
        <img alt="earth-internal-geology" src="https://cdn-icons-png.flaticon.com/512/950/950139.png" title="earth-internal-geology" style="width:40%">
      </div>
    </div>
  </div>


    <!-- Col right-->
  <div class="col-lg-5">
    <!-- Tab panes text-->
    <div class="tab-content">
      <div id="target1" class="container tab-pane{% if active_section == '1' %} active {% endif %}"><br>
        <h3>01 Menu</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
      <div id="target2" class="container tab-pane fade{% if active_section == '2' %} active show {% endif %}"><br>
        <h3>02 Menu</h3>
        <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      </div>
      <div id="target3" class="container tab-pane fade{% if active_section == '3' %} active show {% endif %}"><br>
        <h3>03 Menu</h3>
        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
      </div>
    </div>

    <!-- Nav pills -->
    <ul class="nav nav-pills flex-column col-4" role="tablist">
        <li class="nav-item">
          <a class="nav-link {% if active_section == '1' %} active {% endif %}" href="{% url 'basic_app:relative' look_name=active_tab look_section=1 %}">01</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if active_section == '2' %} active {% endif %}" href="{% url 'basic_app:relative' look_name=active_tab look_section=2 %}">02</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if active_section == '3' %} active {% endif %}" href="{% url 'basic_app:relative' look_name=active_tab look_section=3 %}">03</a>
        </li>
    </ul>
  </div>

</div>


{% endblock %}