the_project/first_app/urls.py
from django.urls import path
from . import views

app_name = 'first_app'

urlpatterns = [
    path('', views.index, name='home'),
    path('first_app/', views.first_app, name='first_app')
]

the_project/the_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_app.urls')),
]

the_project/first_app/models.py
from django.db import models


# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name


class WebPage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name = models.ForeignKey(WebPage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

the_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Topic, WebPage, AccessRecord


# Create your views here.
def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records': webpages_list}

    return render(request, 'first_app/index.html', context=date_dict)


def first_app(request):
    my_dict = {'insert_me': 'Hello from first_app/views.py!!'}
    return render(request, 'first_app/first_app_page.html', context=my_dict)

the_project/templates/first_app/first_app_page.html
<!doctype html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>first_app Page</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <h2>Hi, this is a picture of Django Guitar!</h2>
    <img src="{% static 'images/django_guitar.jpg' %}" alt='Uh oh, unable to show image!' width="20%">

    <div>
        <strong>Text inserted: "{{ insert_me }}"</strong>
        <br>
        <a href="{% url 'first_app:home' %}">Back to home page</a>
    </div>
</body>
</html>

the_project/templates/first_app/index.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django Level Two</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
<h1>Hi! welcome to Django Level two!</h1>
<h2>Here are your access records:</h2>

<div class="djangotwo">
    {% if access_records %}
    <table>
        <thead>
            <th>Site Name</th>
            <th>Date Accessed</th>
        </thead>

        {% for acc in access_records %}
        <tr>
            <td>{{ acc.name }}</td>
            <td>{{ acc.date }}</td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>NO ACCESS RECORDS FOUND!</p>
    {% endif %}

</div>
</body>
</html>

the_project/templates/first_app/original_index.html
<!doctype html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home Page</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <h1>This is home page!</h1>
    <a href="{% url 'first_app:first_app' %}">Go to first_app page</a>
</body>
</html>