the_project_challenge/second_app/urls.py
from django.urls import path
from . import views

app_name = 'second_app'

urlpatterns = [
    path('', views.index, name='home'),
    path('second_app/', views.second_app, name='second_app'),
    path('users/', views.users, name='users')
]

the_project_challenge/the_project_challenge/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('second_app.urls')),
]

the_project_challenge/second_app/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.CharField(max_length=20, null=False, unique=True)

the_project_challenge/second_app/views.py
from django.shortcuts import render
from .models import User


# Create your views here.
def index(request):
    return render(request, 'second_app/index.html')


def second_app(request):
    my_dict = {'insert_me': 'Hello from second_app/views.py!!'}
    return render(request, 'second_app/second_app_page.html', context=my_dict)


def users(request):
    user_list = User.objects.order_by('first_name')
    user_dict = {'access_users': user_list}
    return render(request, 'second_app/users.html', context=user_dict)

the_project_challenge/templates/second_app/index.html
<!doctype html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home Page</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <h1>This is home page!</h1>
    <h2>Check other pages of this app:</h2>

    <a href="{% url 'second_app:second_app' %}">Go to -> second_app page</a> <br>
    <a href="{% url 'second_app:users' %}">Go to -> users page</a>


</body>
</html>

the_project_challenge/templates/second_app/second_app_page.html
<!doctype html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>first_app Page</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <h2>Hi, this is a picture of Django Guitar!</h2>
    <img src="{% static 'images/django_guitar.jpg' %}" alt='Uh oh, unable to show image!' width="20%">

    <div>
        <strong>Text inserted: "{{ insert_me }}"</strong>
        <br>
        <a href="{% url 'second_app:home' %}">Back to home page</a>
    </div>
</body>
</html>

the_project_challenge/templates/second_app/users.html
<!doctype html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Users Page</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <h1>Hello from users page</h1>
    {% if access_users %}

        <ol>
            {% for user in access_users %}
            <li>User Info</li>
                <ul>
                    <li>First Name: {{user.first_name}}</li>
                    <li>Last Name: {{user.last_name}}</li>
                    <li>Email: {{user.email}}</li>
                </ul>
            {% endfor%}
        </ol>

    {% else %}
    <p>NO USERS FOUND!</p>
    {% endif %}
    <br>
    <a href="{% url 'second_app:home' %}">Back to home page</a>
</body>

</html>